version: '3.9'

services:
  samba:
    image: justinpatchett/samba
    container_name: samba
    environment:
      TZ: 'UTC'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    restart: unless-stopped
    tty: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /mnt:/mnt:z
      - /mnt2:/mnt2:z
    command: '-s "Mount;/mnt" -s "Admin Volume;/mnt2;yes;no;no;admin" -u "admin;guest" -p'

networks:
  default: